/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_testcontext_free: (a: number, b: number) => void;
export const testcontext_new: (a: number, b: number, c: number, d: number) => any;
export const testcontext_get_proofs_to_spend: (a: number, b: bigint) => any;
export const testcontext_create_blinded_outputs: (a: number, b: number, c: number) => any;
export const testcontext_create_blinded_outputs_with_conditions: (a: number, b: number, c: number, d: any) => any;
export const testcontext_submit_swap: (a: number, b: any, c: any) => any;
export const testcontext_unblind_signatures: (a: number, b: any, c: any, d: any) => any;
export const testcontext_add_proofs_to_wallet: (a: number, b: any) => any;
export const main: () => void;
export const greet: (a: number, b: number) => [number, number];
export const get_mint_denominations: (a: number, b: number) => any;
export const check_nut11_support: (a: number, b: number) => any;
export const generate_wallet_seed: () => [number, number];
export const create_wallet: (a: number, b: number, c: number, d: number) => any;
export const mint_tokens: (a: number, b: number, c: number, d: number, e: number, f: number) => any;
export const get_wallet_balance_by_state: (a: number, b: number, c: number, d: number) => any;
export const create_token: (a: number, b: number, c: number, d: number, e: bigint) => any;
export const get_wallet_balance: (a: number, b: number, c: number, d: number) => any;
export const generate_test_keypairs: () => [number, number, number];
export const create_mint_quote: (a: number, b: number, c: number, d: number, e: bigint) => any;
export const check_mint_quote_status: (a: number, b: number, c: number, d: number, e: number, f: number) => any;
export const swap_to_p2pk_2of2: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: any, j: number) => any;
export const add_proofs_to_wallet: (a: number, b: number, c: number, d: number, e: any) => any;
export const check_specific_proofs_state: (a: number, b: number, c: any) => any;
export const check_proofs_state: (a: number, b: number, c: number, d: number) => any;
export const swap_with_sig_all: (a: number, b: number, c: any, d: number, e: number) => any;
export const swap_with_p2pk: (a: number, b: number, c: any, d: number, e: number) => any;
export const sign_proofs_with_sig_all: (a: number, b: number, c: any, d: number, e: number) => any;
export const submit_signed_proofs: (a: number, b: number, c: any) => any;
export const create_blinded_outputs: (a: number, b: number, c: number, d: number) => any;
export const create_blinded_outputs_with_p2pk: (a: number, b: number, c: number, d: number, e: any) => any;
export const create_spending_conditions_p2pk_2of2: (a: number, b: number, c: number, d: number, e: number, f: bigint) => [number, number, number];
export const create_spending_conditions_with_locktime_refund: (a: number, b: number, c: number, d: number, e: bigint) => [number, number, number];
export const create_spending_conditions_multisig_locktime: (a: number, b: number, c: number, d: number, e: number, f: number, g: bigint, h: bigint, i: bigint) => [number, number, number];
export const create_swap_request: (a: any, b: any) => [number, number, number];
export const sign_swap_request_sigall: (a: any, b: number, c: number) => [number, number, number];
export const sign_swap_request_p2pk: (a: any, b: number, c: number) => [number, number, number];
export const submit_swap_request: (a: number, b: number, c: any) => any;
export const unblind_signatures: (a: number, b: number, c: any, d: any, e: any) => any;
export const rustsecp256k1_v0_10_0_context_create: (a: number) => number;
export const rustsecp256k1_v0_10_0_context_destroy: (a: number) => void;
export const rustsecp256k1_v0_10_0_default_illegal_callback_fn: (a: number, b: number) => void;
export const rustsecp256k1_v0_10_0_default_error_callback_fn: (a: number, b: number) => void;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_2: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_export_6: WebAssembly.Table;
export const __externref_table_dealloc: (a: number) => void;
export const wasm_bindgen__convert__closures_____invoke__h57d8dd306e15d6a6: (a: number, b: number) => void;
export const closure1034_externref_shim: (a: number, b: number, c: any) => void;
export const closure1955_externref_shim: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_start: () => void;
